### ISSUE TITLE
Use of Training n_epoch

### ISSUE THREAD

**Issue by jpatra72** [asaran/VeSSAL#2]
Hi Akanksha, 

I noticed that even though the n_epoch is defined at [ln. 52](https://github.com/asaran/VeSSAL/blob/00ea867fc10a330613cf34ce106245d1f2aaf444/run.py#L52) it is not being used in training the model [ln. 54](https://github.com/asaran/VeSSAL/blob/00ea867fc10a330613cf34ce106245d1f2aaf444/query_strategies/strategy.py#L54). 

Is this intentional? Wouldn't it lead to overfitting of the model to the train data (especially when it is small) since the train stop condition ([ln. 64](https://github.com/asaran/VeSSAL/blob/00ea867fc10a330613cf34ce106245d1f2aaf444/query_strategies/strategy.py#L64)) is dependent if the model reaches a predefined accuracy thershold?

Looking forward to your reply.

**Comment by JordanAsh** [comment]
Hi,

Like in the original [BADGE](https://github.com/JordanAsh/badge) library, we train until the model gets within 99% training accuracy. The n_epochs number is just an artifact of the [repository that BADGE was based on](https://github.com/ej0cl6/deep-active-learning). We don't use regularizers of any kind, including early stopping, because we want to highlight the effect of the decision-making algorithm in isolation. Anecdotally, we don't observe much overfitting on these datasets — improvements in training performance tend to correspond to improvements in test performance even though there's a gap between the two.

If you're using this library for industrial applications, we'd suggest investigating regularizers to get the highest performance possible. If you're using it for academic research, and you're more interested in the relative performance of decision-making algorithms than maximizing the absolute performance of any one algorithm, we we would recommend this strategy.

Best,
Jordan
